Repository TechNodes2-0/TechNode-Community-Website, pull requests merged in 2023-10, with the labels that each got.

#8 fix: color and Update the team section
  Technodes/src/Pages/Team.jsx
  Technodes/tailwind.config.js
Labels: good first issue, frontend, hacktoberfest

#9 fix: Homepage
  Technodes/package-lock.json
  Technodes/package.json
  Technodes/src/components/HeroSection.jsx
  Technodes/src/index.css
  Technodes/tailwind.config.js
  Technodes/vite.config.js
Labels: frontend, hacktoberfest, hacktoberfest-accepted

#11 feat: About Us Page✨
  Technodes/package-lock.json
  Technodes/package.json
  Technodes/src/Pages/Home.jsx
  Technodes/src/components/core/Aboutus.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#13 searching and sorting added in project section
  Technodes/src/Pages/Projects.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#12 Updated "Get In Touch" section in Contact.jsx for issue #10
  Technodes/src/Pages/Contact.jsx
Labels: hacktoberfest, SLoP3-75, hacktoberfest-accepted

#17 UI and Link Fix on Contact Us Page
  Technodes/src/Pages/Contact.jsx
  Technodes/src/components/Footer.jsx
Labels: hacktoberfest, SLoP3-100, hacktoberfest-accepted
